{{
    config(
        materialized='view',
        schema='platinum',
        tags=['platinum', 'scout', 'ai-ready', 'embeddings'],
        post_hook=[
            "COMMENT ON VIEW {{ this }} IS 'AI-ready transaction data with text embeddings for RAG and semantic search'"
        ]
    )
}}

-- Platinum layer: AI-ready transaction data with embeddings
-- Purpose: Semantic search, RAG, LLM context, recommendations
-- Embeddings generated via LiteLLM (text-embedding-3-small or similar)

WITH transaction_text AS (
    SELECT
        id,
        transaction_id,
        transaction_date,
        amount,
        currency,
        category,
        subcategory,
        vendor_name,
        description,
        -- Create rich text representation for embedding
        CONCAT(
            'Transaction on ', transaction_date::TEXT,
            ' at ', vendor_name,
            ' for ', category,
            CASE WHEN subcategory IS NOT NULL THEN ' (' || subcategory || ')' ELSE '' END,
            '. Amount: ', currency, ' ', amount::TEXT,
            CASE WHEN description IS NOT NULL THEN '. ' || description ELSE '' END
        ) AS embedding_text,
        -- Metadata for filtering and context
        jsonb_build_object(
            'transaction_id', transaction_id,
            'date', transaction_date,
            'amount', amount,
            'currency', currency,
            'category', category,
            'subcategory', subcategory,
            'vendor', vendor_name,
            'tax_code', tax_code,
            'employee_id', employee_id,
            'cost_center', cost_center
        ) AS metadata
    FROM {{ ref('silver_validated_transactions') }}
    WHERE transaction_date >= CURRENT_DATE - INTERVAL '90 days'
),

embeddings_data AS (
    SELECT
        id,
        transaction_id,
        embedding_text AS text,
        -- Placeholder for embeddings (generated by LiteLLM pipeline)
        -- In production, this would be populated by:
        -- 1. n8n workflow calling LiteLLM embedding endpoint
        -- 2. Airflow DAG with embedding generation task
        -- 3. Edge Function trigger on insert
        NULL::vector(1536) AS embedding,
        metadata,
        transaction_date,
        amount,
        category,
        vendor_name,
        CURRENT_TIMESTAMP AS generated_at
    FROM transaction_text
)

SELECT * FROM embeddings_data

-- Note: Embeddings are stored in separate table `scout.platinum_transaction_embeddings`
-- with pgvector extension enabled for similarity search
-- This view provides the source data for embedding generation
